### ISSUE TITLE
Tip 实现图片画廊中用到的知识点

### ISSUE THREAD

**Issue by 7986LiChang** [7986LiChang/gallery-by-react#4]
**1、bind实现函数调用**
bind:  在函数调用时，传入绑定的对象
```js
class AppComponent extends React.Component{
       render(){
       }
       
       inverse(index){
             return   function(){}.bind(this);    //通过bind调用函数，传入AppComponent对象
       }
       function(){}.bind(this)
}
```

**2、CSS3  3D转换  transform**
css 变换坐标系：（默认以元素中心为（0,0,0），也是（50% 50% 0）（center center 0））
![qq 20170714101738](https://user-images.githubusercontent.com/14882636/28195645-246f4eee-687e-11e7-9c57-bd1066b4d93b.png)

```css

transform: rotateX(30deg) //元素围绕X轴以给定度数旋转，正数顺时针
transform: rotateY(angle) //元素围绕Y轴以给定度数旋转
transform: rotateZ(angle) //元素围绕Z轴以给定度数旋转
transform: rotate3d(tx, ty, tz, deg)  //以向量(tx, ty, tz)为轴旋转deg，正为顺时针
```

```css
transform-origin: 50% 50% 0  //设定元素旋转的基点位置，默认为元素中心。z轴取值只能是长度

transform-style: preserve-3d | flat   //子元素保留/不保留其3D位置
```

```css
//父元素中设置
perspective: 500   //规定3D元素的透视效果，定义3D元素距视图的距离，以像素计。。。是子元素获得透视效果
perspectve-origin: x-axis y-axis   //改变3D元素的底部位置，定义基于的X轴、Y轴。。。默认值50% 50%
```
```css
backface-visibility: visible | hidden  //设置旋转元素背面是否可见
```

**例如：**
```css
//将图片组件翻转到背面
.img-figure{
         transform: rotateY(180deg);    //在默认中心基点，绕Y轴旋转180度
}
```

**3、css3过渡  transition**
transition-property   应用过渡的css属性名称
transition-duration   过渡效果花费的时间，默认为0
transition-timing-function   过渡效果的时间曲线，默认是“ease”
transition-delay    过渡效果从何时开始
```css
transition: width 1s linear 2s;   应用于width属性，2s后开始，持续1s，速度曲线为linear
```
transition-timing-function 规定过渡效果的速度曲线，允许过渡效果随时间改变速度
可取得值有：
linear             相同速度从开始到结束                                   cubic-bezier(0,0,1,1)
ease              慢速开始，中间变快，慢速结束                     cubic-bezier(0.25,0.1,0.25,1)
ease-in          慢速开始                                                         cubic-bezier(0.42,0,1,1)
ease-out        慢速结束                                                        cubic-bezier(0,0,0.58,1)
ease-in-out    慢速开始和结束                                             cubic-bezier(0.42,0,0.58,1)
cubic-bezier(n,n,n,n)  贝塞尔曲线中自定义时间速度变化   

**4、关于sass**

- SASS是一种CSS的开发工具，提供了很多便利的写法，使得CSS的开发简单易维护
- sass最典型的特性：为css引入了变量，可以通过变量名引用需要反复使用的css 属性，使用$声明变量
- sass文件有两种后缀：  style.sass其中不适用大括号和分号     style.scss类似平时写的css文件，使用大括号和分号
- 使用&引用父元素
- 选择器与属性都可以嵌套。
  (1) 例如：选择器嵌套，将层级选择器用嵌套形式表示
```css
//css
#top_nav{
  line-height: 40px;
  background-color: #333;
}

#top_nav li{
    float: left;
}  
#top_nav a{
    display: block;
    padding: 0 10px;
    color: #fff;
}
#top_nav a:hover{
      color:#ddd;
}
```

```sass
//sass
#top_nav{
  line-height: 40px;
  background-color: #333;
  li{
    float: left;
  }  
  a{
    display: block;
    padding: 0 10px;
    color: #fff;

    &:hover{
      color:#ddd;
    }
   }
}
```

(2) 属性嵌套，嵌套的属性名后要加：
```css
//css
.fakeshadow {
  border-style: solid;
  border-left-width: 4px;
  border-left-color: #888;
  border-right-width: 2px;
  border-right-color: #ccc; 
}
```

```sass
//sass
.fakeshadow {
  border: {
      style: solid;
      left: {
          width: 4px;
          color: #888;
      }
      right: {
          width: 2px;
          color: #ccc;
      }
  }
}
```
- @at-root跳出嵌套， 跳出所有上级选择器
```sass
//普通嵌套
.parent-1 {
  color:#f00;
  .child {
    width:100px;
  }
}

.parent-1 {
  color: #f00;
}
.parent-1 .child {
  width: 100px;
}
```

```css
//使用@at-root跳出嵌套
.parent-3 {
  background:#f00;
  @at-root {
    .child1 {
      width:300px;
    }
    .child2 {
      width:400px;
    }
  }
}

.parent-3 {
  background: #f00;
}
.child1 {
  width: 300px;
}
.child2 {
  width: 400px;
}
```

**5、代码调试**
在代码行中添加 debugger；进入调试模式
      可以查看各个变量情况
